---
- name: install openssh
  portage: package=net-misc/openssh
  tags: packages

- name: configure sshd
  template: >
    src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=root group=root mode=0600
    validate="/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  tags: config

- name: Set up multiple authorized keys
  authorized_key:
    user: gentoo
    state: present
    key: '{{ item }}'
    path: /etc/ssh/authorized_keys/gentoo
    manage_dir: True
  with_file:
    - public_keys/blueness
    - public_keys/nerdboy
    - public_keys/gbarker
    - public_keys/kul
  tags: [config, security]

- name: remove old keys file if present
  file: path=/home/gentoo/.ssh/authorized_keys state=absent

- name: enable and start sshd
  service: name=sshd enabled=true state=started
