---
- name: install openssh
  portage: package=net-misc/openssh
  tags: packages

- name: configure sshd
  template: >
    src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=root group=root mode=0600
    validate="/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  tags: configuration

- name: manage ssh keys
  template: >
    src=authorized_keys.j2
    dest=/etc/ssh/authorized_keys
    owner=root group=root mode=0644
  tags: configuration

- name: enable and start sshd
  service: name=sshd enabled=true state=started
